"""fix omni_ai_agent_configs/omni_tags owner_id index drift

Revision ID: 3eb6838d3b1b
Revises: c3d4e5f6a7b8
Create Date: 2026-08-14 22:47:01.294618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb6838d3b1b'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_omni_ai_agent_config_owner'), 'omni_ai_agent_configs', type_='unique')
    op.create_index(op.f('ix_omni_ai_agent_configs_owner_id'), 'omni_ai_agent_configs', ['owner_id'], unique=True)
    op.create_index(op.f('ix_omni_tags_owner_id'), 'omni_tags', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_omni_tags_owner_id'), table_name='omni_tags')
    op.drop_index(op.f('ix_omni_ai_agent_configs_owner_id'), table_name='omni_ai_agent_configs')
    op.create_unique_constraint(op.f('uq_omni_ai_agent_config_owner'), 'omni_ai_agent_configs', ['owner_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
