"""add referral link to users and campaigns

Revision ID: 6ad75c20ec09
Revises: 3eb6838d3b1b
Create Date: 2026-08-15 01:04:01.700989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad75c20ec09'
down_revision: Union[str, None] = '3eb6838d3b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default required here (unlike the plain add_column below): campaigns
    # already has rows in production, and a NOT NULL column needs a value for
    # them - dropped right after, same two-step pattern as
    # b2c3d4e5f6a7_add_omni_customer_is_blocked.py.
    op.add_column('campaigns', sa.Column('include_referral_link', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('campaigns', 'include_referral_link', server_default=None)
    op.add_column('users', sa.Column('referral_link', sa.String(length=1000), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referral_link')
    op.drop_column('campaigns', 'include_referral_link')
    # ### end Alembic commands ###
