"""add social_channel external_link

Revision ID: 86cc88b95e20
Revises: 7dffc5a8e64c
Create Date: 2026-07-23 01:29:41.599423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86cc88b95e20'
down_revision: Union[str, None] = '7dffc5a8e64c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_channels', sa.Column('external_link', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_channels', 'external_link')
    # ### end Alembic commands ###
