"""add blog writer module

Revision ID: f4deed527dc6
Revises: f6ddf5f364f6
Create Date: 2026-07-23 06:41:43.566303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4deed527dc6'
down_revision: Union[str, None] = 'f6ddf5f364f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_writer_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('excerpt', sa.String(length=1000), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_keyword', sa.String(length=255), nullable=True),
    sa.Column('secondary_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('target_audience', sa.String(length=255), nullable=True),
    sa.Column('article_goal', sa.String(length=255), nullable=True),
    sa.Column('generation_prompt', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generation_model', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['administrators.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_writer_wordpress_sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('site_url', sa.String(length=1000), nullable=False),
    sa.Column('api_url', sa.String(length=1000), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('encrypted_application_password', sa.String(length=1000), nullable=False),
    sa.Column('default_author_id', sa.Integer(), nullable=True),
    sa.Column('default_author_name', sa.String(length=255), nullable=True),
    sa.Column('default_category_id', sa.Integer(), nullable=True),
    sa.Column('default_category_name', sa.String(length=255), nullable=True),
    sa.Column('default_status', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('connection_status', sa.String(length=20), nullable=False),
    sa.Column('last_connection_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_connection_error', sa.String(length=1000), nullable=True),
    sa.Column('last_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_writer_publications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('wordpress_site_id', sa.UUID(), nullable=False),
    sa.Column('wordpress_post_id', sa.Integer(), nullable=True),
    sa.Column('wordpress_post_url', sa.String(length=1000), nullable=True),
    sa.Column('wordpress_status', sa.String(length=20), nullable=True),
    sa.Column('publication_status', sa.String(length=20), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['blog_writer_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wordpress_site_id'], ['blog_writer_wordpress_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'wordpress_site_id', name='uq_blog_publication_article_site')
    )
    op.add_column('campaigns', sa.Column('article_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'campaigns', 'blog_writer_articles', ['article_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'article_id')
    op.drop_table('blog_writer_publications')
    op.drop_table('blog_writer_wordpress_sites')
    op.drop_table('blog_writer_articles')
    # ### end Alembic commands ###
