"""add ai_settings table

Revision ID: f6ddf5f364f6
Revises: 86cc88b95e20
Create Date: 2026-07-23 02:20:38.252100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ddf5f364f6'
down_revision: Union[str, None] = '86cc88b95e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('openai_api_key_encrypted', sa.String(length=1000), nullable=True),
    sa.Column('openai_model', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_settings')
    # ### end Alembic commands ###
