"""add blog_writer_articles media_file_id

Revision ID: f977e27daa7d
Revises: f4deed527dc6
Create Date: 2026-07-23 08:04:46.139173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f977e27daa7d'
down_revision: Union[str, None] = 'f4deed527dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_writer_articles', sa.Column('media_file_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'blog_writer_articles', 'media_files', ['media_file_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_writer_articles', type_='foreignkey')
    op.drop_column('blog_writer_articles', 'media_file_id')
    # ### end Alembic commands ###
